# Generated by Django 3.2 on 2021-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
